### PR TITLE
Fix: add source files needed to generate the site

### PR DESCRIPTION
**Pull request by jcstr**
1. Why is this change neccesary?
This commit add the source files needed to build the website with hugo
and deletes the old files from the old theme.

2. How does it address the issue?
This commit only focus on the source files needed to build the website.
The rendered website will be on another branch.

3. What side effects does this change have?
None.

### CODE REVIEW

**Review by denisse-dev — CHANGES_REQUESTED** [review]
We need the source files to generate the website, not just the generated website.

**Review by SantiagoTorres — APPROVED** [review]
LGTM!

**Review by denisse-dev — CHANGES_REQUESTED** [review]
This looks pretty good to me however, the commit message could be improved.
Could you please change the title of the commit from _Rebase: combine the last 5 commits on this one_ to something like _feature: Add Hugo project files needed to generate the site_ ?

Screen Shot 2020-10-29 at 10 39 36

**Comment by jcstr** [comment]
@da-edra Done! 😄

**Review by denisse-dev — APPROVED** [review]
:1st_place_medal:

**Pull request merged**
