### PR TITLE
Add a proper theme

### PR DESCRIPTION
**Pull request by jcstr**
1. Why is this change necessary?
This change adds a proper theme, following the Arch Linux website style.

2. How does it address the issue?
It replaces the old theme which was intended for testing purposes.
 
3. What side effects does this change have?
Particularly on behalf for a new UI that follows the styling of the official Arch Linux website.

Adding a screenshot about the new theme:

image

### CODE REVIEW

**Review by denisse-dev — CHANGES_REQUESTED** [review]
Hello, thanks for your pull request. Where are the source files to generate the static site?

We need to have source code to generate this and not only the generated static website.
Please refer to [this](https://gohugo.io/hosting-and-deployment/hosting-on-github/) documentation and create a new pull request.

Since this pull request would involve a GUI it's important to attach screenshots of how it looks like or instructions on how to render this.

Another thing, please add more descriptive commit messages, you can use [this](https://github.com/da-edra/dotfiles/blob/master/.gitmessage) template for reference.

Thanks. 😸

**Comment by denisse-dev** [comment]
Please refer to [this](https://chris.beams.io/posts/git-commit/) resource so you can write better commit messages.
Feel free to ask me if you have any doubts.

**Comment by jcstr** [comment]
Following your suggestions I've edited the comment adding more details and a screenshot.

**Comment by jcstr** [comment]
Following the resources to deploy the website to GitHub I may broke the local repository, following each step I've deleted the 'public' folder to update the website with the new theme, now, when I'm trying to run the script to deploy this is the output message:
```
Deploying updates to GitHub...
Start building sites … 
WARN 2020/10/19 00:46:00 Page.Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2020/10/19 00:46:00 Page.RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}

                   | EN   
-------------------+------
  Pages            |   7  
  Paginator pages  |   0  
  Non-page files   |   0  
  Static files     | 189  
  Processed images |   0  
  Aliases          |   1  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 236 ms
fatal: in unpopulated submodule 'public'

```

I need help to work with git submodules.

Thanks in advance

**Comment by denisse-dev** [comment]
Thanks for updating the comment @jcstr but you must update the **commit message**, the comment you leave on the PR is only relevant to the PR and does not belong to the source tree of the repository.

If you take a look at your commit you can see that the message is the same, and we need a meaningful commit message (this in turns generates a meaningful comment).

I'll write to you to help you with Git submodules and I'll show you how to amend your commit.

Cheers! 

Screen Shot 2020-10-19 at 1 16 15

**Comment by denisse-dev** [comment]
Another thing, it's not necessary to add `Signed-off-by: Jesús Castro <x51v4n@gmail.com>` to your commit messages.
If you've configured your git credentials correctly they'll be shown whenever a user performs a `git log` command, I'm attaching a screenshot so you can see how my name and email address are shown when performing `git log` in a repository I've committed to.

Screen Shot 2020-10-19 at 1 19 05

**Review by SantiagoTorres — CHANGES_REQUESTED** [review]
It seems to be that a large part of these files are generated files (or static files). I wonder if instead of checking them in, we can use the build harness to fetch these and add them to the rendered website?

**Comment by jcstr** [comment]
@SantiagoTorres Actually I'm working on another branch which will show the entire repository, this branch only contains the generated site (html) that remains on the `public` folder. 

Following your comment I was adding this by performing the `hugo -D` command and I've realized that I forgot to delete all the files of the old theme. This is why I've worked with this by hand but it's not complete yet.

The expected result is something like:
from the repository:
branch `main`: all the source files that are needed to generate the html files.
branch `gh-pages`: the generated site up and running under GitHub Pages.

**Pull request closed without merging**
